# Generated by Django 4.2 on 2023-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userdata_options_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
