# Generated by Django 4.2 on 2023-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproducts_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='order_products',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
