# Generated by Django 4.2 on 2023-05-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='order_products',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
