# Generated by Django 4.2 on 2023-05-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_city_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproducts',
            old_name='product_current_price',
            new_name='product_price',
        ),
    ]
