# Generated by Django 4.2 on 2023-05-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_product_current_price_orderproducts_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
