# Generated by Django 4.2 on 2023-05-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderproducts_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name_plural': 'OrderProducts'},
        ),
    ]
