# Generated by Django 4.2 on 2023-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_created_order_modified_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
