# Generated by Django 4.2 on 2023-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_product_count_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
