# Generated by Django 4.2 on 2023-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_order_product_count_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Waiting for payment'), (2, 'Waiting for sending'), (3, 'Sent'), (4, 'Delivered')], default=1, max_length=40),
        ),
    ]
