# Generated by Django 4.2 on 2023-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Waiting for payment'), ('2', 'Waiting for sending'), ('3', 'Sent'), ('4', 'Delivered')], default='1', max_length=40),
        ),
    ]
