# Generated by Django 4.2 on 2023-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_stripe_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
