# Generated by Django 4.2 on 2023-04-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainImage',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='main_img', serialize=False, to='products.product')),
                ('main_img', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productimage')),
            ],
        ),
    ]
