# Generated by Django 4.2 on 2023-04-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productshoe_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('1', 'Shoe'), ('2', 'Suit'), ('3', 'Shirt')], max_length=3),
        ),
        migrations.AlterField(
            model_name='productshoe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productshoe',
            unique_together={('product', 'size', 'color')},
        ),
        migrations.CreateModel(
            name='ProductSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('height_cm', models.DecimalField(decimal_places=0, max_digits=3)),
                ('chest_cm', models.DecimalField(decimal_places=0, max_digits=3)),
                ('waist_cm', models.DecimalField(decimal_places=0, max_digits=3)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'height_cm', 'chest_cm', 'waist_cm', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('height_cm', models.DecimalField(decimal_places=0, max_digits=3)),
                ('collar_cm', models.DecimalField(decimal_places=0, max_digits=3)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'height_cm', 'collar_cm', 'color')},
            },
        ),
    ]
