# Generated by Django 4.2 on 2023-04-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='main',
        ),
    ]
