# Generated by Django 4.2 on 2023-04-26 13:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=products.models.get_thumbnail_path),
            preserve_default=False,
        ),
    ]
