# Generated by Django 4.2 on 2023-04-25 13:50

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimages',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='img',
            field=models.ImageField(upload_to=products.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
