# Generated by Django 4.2 on 2023-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_type_productbackpack'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='productbackpack',
        #    unique_together=set(),
        # ),
        migrations.AddField(
            model_name='productbackpack',
            name='waterproof',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=20),
            preserve_default=False,
        ),
        # migrations.AlterUniqueTogether(
        #     name='productbackpack',
        #     unique_together={('product', 'color', 'waterproof')},
        # ),
    ]
