# Generated by Django 4.2 on 2023-06-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_waterproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbackpack',
            name='waterproof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.waterproof'),
        ),
    ]
